---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apps-frank-com-v1-frank
  failurePolicy: Fail
  name: mfrank.kb.io
  rules:
  - apiGroups:
    - apps.frank.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - franks
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apps-frank-com-v1-frank
  failurePolicy: Fail
  name: vfrank.kb.io
  rules:
  - apiGroups:
    - apps.frank.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - franks
  sideEffects: None
